/**
 * `docs/CONFIG-REFERENCE.md`: every key of `loadline.json` as tables, written from the schema.
 *
 * The guide (`docs/CONFIG.md`) is written by hand, because it is about what somebody wants to do.
 * This half is about what exists, and that is exactly the half that goes stale when it is typed: a
 * threshold added, a recommended value moved, a signal renamed. So it comes out of the same
 * functions as `loadline.schema.json`, and `cli/config-files.spec.ts` fails when either is out of date.
 */

import { CRITERIA_FIELDS } from '../criteria/criteria';
import { type CriteriaField } from '../criteria/criteria.types';
import { FINDING_KINDS } from '../findings/finding.types';
import { UI } from '../i18n/ui';
import { configSchema, criterionText, KIND_NAMES } from './config-schema';

type Schema = Record<string, unknown>;

const describe = (schema: unknown): string => {
    const text = (schema as Schema | undefined)?.['description'];
    return typeof text === 'string' ? text.replaceAll('|', String.raw`\|`) : '';
};

const table = (head: string[], rows: string[][]): string[] => [
    `| ${head.join(' | ')} |`,
    `| ${head.map(() => '---').join(' | ')} |`,
    ...rows.map(row => `| ${row.join(' | ')} |`),
];

const propertiesOf = (schema: unknown): [string, Schema][] =>
    Object.entries(((schema as Schema | undefined)?.['properties'] ?? {}) as Record<string, Schema>);

const GROUPS: { group: CriteriaField['group']; title: (en: typeof UI.en) => string }[] = [
    { group: 'sizes', title: en => en.critGroupSizes },
    { group: 'shared', title: en => en.critGroupShared },
    { group: 'signals', title: en => en.critGroupSignals },
    { group: 'shape', title: en => en.critGroupShape },
    { group: 'context', title: en => en.critGroupContext },
];

export const configReference = (): string => {
    const schema = configSchema();
    const top = Object.fromEntries(propertiesOf(schema));

    const criteriaSections = GROUPS.flatMap(({ group, title }) => {
        const keys = CRITERIA_FIELDS.filter(field => field.group === group).flatMap(field =>
            field.pairWith ? [field.key, field.pairWith] : [field.key],
        );
        return [
            '',
            `### ${title(UI.en)}`,
            '',
            ...table(
                ['Key', 'What it does', 'gzip', 'brotli', 'raw'],
                keys.map(key => {
                    const { what, recommended } = criterionText(key);
                    return [
                        `\`${key}\``,
                        what.replaceAll('|', String.raw`\|`),
                        recommended.gzip,
                        recommended.brotli,
                        recommended.raw,
                    ];
                }),
            ),
        ];
    });

    const accepted = Object.fromEntries(propertiesOf(top['accepted']?.['items']));
    const situation = propertiesOf(top['situation']);
    const forbidden = propertiesOf(top['forbidden']?.['items']);

    return [
        '# loadline.json — reference',
        '',
        '<!-- Generated by cli/config-files.spec.ts from the code that reads the file. -->',
        '<!-- Do not edit by hand: change the code, then run `pnpm test`. -->',
        '',
        'Every key the file can have, what it does and its recommended value. To learn how to use them,',
        'start with the [guide](CONFIG.md). Your editor shows all of this as you type once the file starts',
        'with `"$schema": "https://unpkg.com/@bymaksym/loadline/loadline.schema.json"`.',
        '',
        'Sizes are written `"350kB"`, `"1.5MB"` or as bytes. Shares are written `"25%"` or as a fraction',
        '(`0.25`). A bare number under 1000 is refused as a size: `350` would be 350 bytes.',
        '',
        '## Top level',
        '',
        ...table(
            ['Key', 'What it is'],
            propertiesOf(schema).map(([key, value]) => [`\`${key}\``, describe(value)]),
        ),
        '',
        '## `gates`',
        '',
        describe(top['gates']),
        '',
        ...table(
            ['Key', 'What it does'],
            propertiesOf(top['gates']).map(([key, value]) => [`\`${key}\``, describe(value)]),
        ),
        '',
        '## `criteria`',
        '',
        describe(top['criteria']),
        '',
        'The three last columns are the recommended values in each unit. Write the ones of the unit your',
        'report is in, and set `mode` to it so a reader knows which they are.',
        ...criteriaSections,
        '',
        '## `accepted`',
        '',
        describe(top['accepted']),
        '',
        ...table(
            ['Field', 'What it is'],
            Object.entries(accepted).map(([key, value]) => [`\`${key}\``, describe(value)]),
        ),
        '',
        '### Signals `kind` can name',
        '',
        ...table(
            ['`kind`', 'Signal'],
            FINDING_KINDS.map(kind => [`\`${kind}\``, KIND_NAMES[kind]]),
        ),
        '',
        '## `forbidden`',
        '',
        describe(top['forbidden']),
        '',
        ...table(
            ['Field', 'What it is'],
            forbidden.map(([key, value]) => [`\`${key}\``, describe(value)]),
        ),
        '',
        '## `situation`',
        '',
        describe(top['situation']),
        '',
        ...table(
            ['Key', 'Question', 'Answers'],
            situation.map(([key, value]) => {
                const options = (value['enum'] as string[] | undefined) ?? [];
                const words = (value['enumDescriptions'] as string[] | undefined) ?? [];
                const answers = options
                    .map((option, index) => `\`${option}\` ${words[index] ?? ''}`.trim())
                    .join('<br>');
                return [`\`${key}\``, describe(value), answers || String(value['type'])];
            }),
        ),
        '',
    ].join('\n');
};
