/**
 * What each signal is, in the words its card uses, in both languages.
 *
 * A `Record` over every kind, so a signal added without a name here does not compile. The schema
 * of `loadline.json` describes what `accepted` can name with the English half. The report uses
 * both halves wherever it names a signal without its card at hand: one that went away since the
 * baseline has no card any more, and "No longer raised: `cycles`, `dupes`" named two identifiers
 * where it meant two problems.
 */

import { type Lang } from '../i18n/ui-strings';
import { type FindingKind } from './finding.types';
import { mono } from './text/finding-html';

export const KIND_NAMES: Record<Lang, Record<FindingKind, string>> = {
    en: {
        shared: 'common code marked as lazy',
        bootLazy: 'bootstrap for a lazy screen',
        bootSingle: 'bootstrap package with a single importer',
        bigFile: 'large source file',
        dupes: 'duplicate copies of a package',
        heavy: 'expensive screen',
        clean: 'no signals',
        commonJs: 'CommonJS package',
        ownInBoot: 'your own code in the bootstrap for a lazy screen',
        locales: 'every language of a library',
        dataAsCode: 'data shipped as code',
        sourceMaps: 'source maps in the folder',
        noSourceMaps: 'folder without source maps',
        splitDrift: 'the breakdown does not add up to the file',
        prefetched: 'screens fetched before anybody asks',
        unreachable: 'chunks this report cannot reach',
        mixedImport: 'imported both statically and dynamically',
        ownBarrel: 'barrel file of your own in the bootstrap',
        packageBarrel: 'package that comes in whole',
        cycles: 'import cycles',
        paidTwice: 'bytes paid for twice',
        twinScreens: 'twin screens',
        theirs: 'whose first load this is',
        fonts: 'fonts',
        media: 'images and video',
        duplicateAssets: 'the same file under two names',
        unreferencedAssets: 'files nothing reaches',
        inlinedData: 'files embedded as data URIs',
        updateWeight: 'weight of the update',
        unstableChunk: 'chunk mixing what changes with what does not',
        unhashable: 'names that cannot be cached',
        secrets: 'secrets or internal addresses in the bundle',
        devLeftovers: 'development leftovers in production',
        sourceExposed: 'your source code is published',
        thirdParty: 'third-party services',
        licences: 'licences with conditions',
        vulnerable: 'vulnerabilities that actually ship',
        transitive: 'packages you did not ask for',
        forbidden: 'forbidden in loadline.json',
        bootWaves: 'bootstrap in several round trips',
        slowScreens: 'discovery depth',
        manyRequests: 'granularity of the split',
        bootGrew: 'bootstrap has grown',
        bootNewPackages: 'new package in the bootstrap',
        sharedGrew: 'shared chunk has grown',
        signalsChanged: 'signals fixed and new',
        screensGrew: 'screen has grown',
        budgetNone: 'no size budget',
        budgetNotBuilt: 'budget the pipeline never applies',
        budgetWarnOnly: 'budget that only warns',
        budgetTooHigh: 'budget too high',
        zoneless: 'no zone.js',
        assetOrigin: 'assets served from another host',
        cascadeShape: 'hash cascade',
        servedUncompressed: 'JavaScript served uncompressed',
        measuredWaves: 'more batches than computed',
        poolExhausted: 'the connection pool ran out',
        thirdPartyLoad: 'third-party requests in the same load',
        revalidated: 'hashed files being revalidated',
        swControlling: 'a service worker controls this load',
        measuredOrigin: 'the code came from another host',
        observedChannel: 'observed environment',
        measuredEager: 'the router loads an area the guard then rejects',
        measuredExtra: 'measured above computed',
        measuredShort: 'measured below computed',
        measuredMatch: 'computed and measured agree',
        situationAsked: 'the situation, answered',
        situationPriority: 'which wait the team would rather pay',
        situationMissing: 'questions that would change this report',
    },
    es: {
        shared: 'código común marcado como lazy',
        bootLazy: 'bootstrap para una pantalla lazy',
        bootSingle: 'paquete del arranque con un solo importador',
        bigFile: 'fichero propio grande',
        dupes: 'copias duplicadas',
        heavy: 'pantalla cara',
        clean: 'sin señales',
        commonJs: 'paquete en CommonJS',
        ownInBoot: 'código tuyo en el bootstrap para una pantalla lazy',
        locales: 'todos los idiomas de una librería',
        dataAsCode: 'datos incluidos como código',
        sourceMaps: 'source maps en la carpeta',
        noSourceMaps: 'carpeta sin source maps',
        splitDrift: 'el desglose no cuadra con el fichero',
        prefetched: 'pantallas que se piden antes de que nadie las abra',
        unreachable: 'chunks que el informe no alcanza',
        mixedImport: 'import estático y dinámico a la vez',
        ownBarrel: 'barrel file propio en el bootstrap',
        packageBarrel: 'paquete que entra entero',
        cycles: 'ciclos de importación',
        paidTwice: 'bytes pagados dos veces',
        twinScreens: 'pantallas gemelas',
        theirs: 'de quién es la primera carga',
        fonts: 'tipografías',
        media: 'imágenes y vídeo',
        duplicateAssets: 'el mismo fichero con dos nombres',
        unreferencedAssets: 'ficheros que no alcanza nadie',
        inlinedData: 'ficheros incrustados como data URI',
        updateWeight: 'peso de la actualización',
        unstableChunk: 'chunk que mezcla lo que cambia con lo que no',
        unhashable: 'nombres que no se pueden cachear',
        secrets: 'secretos o direcciones internas en el bundle',
        devLeftovers: 'restos de desarrollo en producción',
        sourceExposed: 'tu código fuente está publicado',
        thirdParty: 'servicios de terceros',
        licences: 'licencias con condiciones',
        vulnerable: 'vulnerabilidades que sí viajan',
        transitive: 'paquetes que no pides tú',
        forbidden: 'prohibido en loadline.json',
        bootWaves: 'el arranque en varias idas y vueltas',
        slowScreens: 'profundidad de descubrimiento',
        manyRequests: 'granularidad del troceado',
        bootGrew: 'el bootstrap ha crecido',
        bootNewPackages: 'paquete nuevo en el bootstrap',
        sharedGrew: 'chunk compartido que ha crecido',
        signalsChanged: 'señales nuevas y resueltas',
        screensGrew: 'pantalla que ha crecido',
        budgetNone: 'sin budget de tamaño',
        budgetNotBuilt: 'budget que el pipeline no aplica',
        budgetWarnOnly: 'budget que solo avisa',
        budgetTooHigh: 'budget demasiado alto',
        zoneless: 'sin zone.js',
        assetOrigin: 'los assets salen de otro host',
        cascadeShape: 'cascada de hashes',
        servedUncompressed: 'JavaScript servido sin comprimir',
        measuredWaves: 'más tandas de las calculadas',
        poolExhausted: 'se agotó el pool de conexiones',
        thirdPartyLoad: 'peticiones a terceros en la misma carga',
        revalidated: 'ficheros con hash que se revalidan',
        swControlling: 'un service worker controla esta carga',
        measuredOrigin: 'el código vino de otro host',
        observedChannel: 'entorno observado',
        measuredEager: 'el router carga una zona antes de que el guard la rechace',
        measuredExtra: 'medido por encima de lo calculado',
        measuredShort: 'medido por debajo de lo calculado',
        measuredMatch: 'calculado y medido coinciden',
        situationAsked: 'la situación, contestada',
        situationPriority: 'qué espera prefiere pagar el equipo',
        situationMissing: 'preguntas que cambiarían este informe',
    },
};

/**
 * Signals named by what each one is, with what it was about: "import cycles, duplicate copies of a
 * package (`lodash`)". A signal that went away has no card left to take its chip from.
 */
export const signalList = (lang: Lang, list: readonly { kind: FindingKind; key: string }[]): string =>
    list.map(item => `${KIND_NAMES[lang][item.kind]}${item.key ? ` (${mono(item.key)})` : ''}`).join(', ');
