/**
 * Turns the two `.woff2` files in `src/assets/fonts` into `src/styles/_fonts.scss`, as data URIs.
 *
 * The selling point of this tool is that it opens with a double click and that nothing leaves your
 * machine. Asking Google Fonts for two stylesheets and two font files broke both halves of that at
 * once: without a network the page changed shape entirely, and with one it made a request to a
 * third party before drawing anything. The icons were embedded for exactly this reason already.
 *
 * Only the `latin` subset of each family is embedded. Both are variable fonts, so one file per
 * family covers every weight the page uses — which is why this costs about 88 kB of base64 and not
 * seven times that.
 *
 * Re-run it (`pnpm run fonts`) after replacing a `.woff2`. The output is generated: it is in
 * `.prettierignore` and `.stylelintignore`, and it is not edited by hand.
 *
 * Usage: node scripts/embed-fonts.mjs
 */
import fs from 'node:fs';
import path from 'node:path';

const SOURCE = path.join('src', 'assets', 'fonts');
const TARGET = path.join('src', 'styles', '_fonts.scss');

/** family -> the file that carries it, and the weights the variable font spans. */
const FACES = [
    { family: 'Archivo', file: 'archivo-latin.woff2', weight: '100 900' },
    { family: 'JetBrains Mono', file: 'jetbrains-mono-latin.woff2', weight: '100 800' },
];

// The `latin` subset as Google Fonts defines it. Written out so the browser knows not to reach for
// this file for a character it does not carry — it falls back to the stack in `--font-ui` instead.
const LATIN =
    'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, ' +
    'U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD';

const faces = FACES.map(({ family, file, weight }) => {
    const data = fs.readFileSync(path.join(SOURCE, file)).toString('base64');
    return `@font-face {
    font-family: '${family}';
    font-style: normal;
    font-weight: ${weight};
    font-display: swap;
    src: url(data:font/woff2;base64,${data}) format('woff2');
    unicode-range: ${LATIN};
}`;
});

const header = `/* ==========================================================================
   GENERATED by scripts/embed-fonts.mjs from src/assets/fonts. Do not edit by hand.

   Archivo and JetBrains Mono, latin subset, both variable. Both are licensed under the SIL Open
   Font License 1.1, which allows embedding.

   They are inlined rather than linked so the page keeps its two promises: it opens from disk with
   no network, and nothing about your build leaves your machine — not even the request that would
   tell a third party you opened it.
   ========================================================================== */\n\n`;

fs.writeFileSync(TARGET, header + faces.join('\n\n') + '\n');

const size = (fs.statSync(TARGET).size / 1024).toFixed(0);
console.log(`${TARGET}: ${size} kB · ${FACES.length} families embedded`);
